
package sayhello.zoli;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SayHelloEndpoint", targetNamespace = "http://zoli.sayhello")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SayHelloEndpoint {


    /**
     * 
     * @param in
     * @return
     *     returns sayhello.zoli.OutputSayHello
     */
    @WebMethod(operationName = "SayHello", action = "http://zoli.sayhello/SayHello")
    @WebResult(name = "outputSayHello", targetNamespace = "http://zoli.sayhello", partName = "out")
    public OutputSayHello sayHello(
        @WebParam(name = "inputSayHello", targetNamespace = "http://zoli.sayhello", partName = "in")
        InputSayHello in);

}
