
package sayhello.zoli;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SayHelloEndpointService", targetNamespace = "http://zoli.sayhello", wsdlLocation = "file:/C:/GitHub/KatiFuse/ZoliHelloWs/src/main/resources/wsdl/Hello.wsdl")
public class SayHelloEndpointService
    extends Service
{

    private final static URL SAYHELLOENDPOINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SAYHELLOENDPOINTSERVICE_EXCEPTION;
    private final static QName SAYHELLOENDPOINTSERVICE_QNAME = new QName("http://zoli.sayhello", "SayHelloEndpointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/GitHub/KatiFuse/ZoliHelloWs/src/main/resources/wsdl/Hello.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SAYHELLOENDPOINTSERVICE_WSDL_LOCATION = url;
        SAYHELLOENDPOINTSERVICE_EXCEPTION = e;
    }

    public SayHelloEndpointService() {
        super(__getWsdlLocation(), SAYHELLOENDPOINTSERVICE_QNAME);
    }

    public SayHelloEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns SayHelloEndpoint
     */
    @WebEndpoint(name = "SayHelloService")
    public SayHelloEndpoint getSayHelloService() {
        return super.getPort(new QName("http://zoli.sayhello", "SayHelloService"), SayHelloEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SayHelloEndpoint
     */
    @WebEndpoint(name = "SayHelloService")
    public SayHelloEndpoint getSayHelloService(WebServiceFeature... features) {
        return super.getPort(new QName("http://zoli.sayhello", "SayHelloService"), SayHelloEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SAYHELLOENDPOINTSERVICE_EXCEPTION!= null) {
            throw SAYHELLOENDPOINTSERVICE_EXCEPTION;
        }
        return SAYHELLOENDPOINTSERVICE_WSDL_LOCATION;
    }

}
