
package org.apache.camel.example.reportincident;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ReportIncidentEndpoint", targetNamespace = "http://reportincident.example.camel.apache.org")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReportIncidentEndpoint {


    /**
     * 
     * @param in
     * @return
     *     returns org.apache.camel.example.reportincident.OutputReportIncident
     */
    @WebMethod(operationName = "ReportIncident", action = "http://reportincident.example.camel.apache.org/ReportIncident")
    @WebResult(name = "outputReportIncident", targetNamespace = "http://reportincident.example.camel.apache.org", partName = "out")
    public OutputReportIncident reportIncident(
        @WebParam(name = "inputReportIncident", targetNamespace = "http://reportincident.example.camel.apache.org", partName = "in")
        InputReportIncident in);

}
