
package org.apache.camel.example.reportincident;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ReportIncidentEndpointService", targetNamespace = "http://reportincident.example.camel.apache.org", wsdlLocation = "file:/C:/GitHub/KatiFuse/WsdlGenerator/src/main/resources/wsdl/report_incident.wsdl")
public class ReportIncidentEndpointService
    extends Service
{

    private final static URL REPORTINCIDENTENDPOINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException REPORTINCIDENTENDPOINTSERVICE_EXCEPTION;
    private final static QName REPORTINCIDENTENDPOINTSERVICE_QNAME = new QName("http://reportincident.example.camel.apache.org", "ReportIncidentEndpointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/GitHub/KatiFuse/WsdlGenerator/src/main/resources/wsdl/report_incident.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REPORTINCIDENTENDPOINTSERVICE_WSDL_LOCATION = url;
        REPORTINCIDENTENDPOINTSERVICE_EXCEPTION = e;
    }

    public ReportIncidentEndpointService() {
        super(__getWsdlLocation(), REPORTINCIDENTENDPOINTSERVICE_QNAME);
    }

    public ReportIncidentEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ReportIncidentEndpoint
     */
    @WebEndpoint(name = "ReportIncidentService")
    public ReportIncidentEndpoint getReportIncidentService() {
        return super.getPort(new QName("http://reportincident.example.camel.apache.org", "ReportIncidentService"), ReportIncidentEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReportIncidentEndpoint
     */
    @WebEndpoint(name = "ReportIncidentService")
    public ReportIncidentEndpoint getReportIncidentService(WebServiceFeature... features) {
        return super.getPort(new QName("http://reportincident.example.camel.apache.org", "ReportIncidentService"), ReportIncidentEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REPORTINCIDENTENDPOINTSERVICE_EXCEPTION!= null) {
            throw REPORTINCIDENTENDPOINTSERVICE_EXCEPTION;
        }
        return REPORTINCIDENTENDPOINTSERVICE_WSDL_LOCATION;
    }

}
